/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.View;

/**
 *
 * @author asus
 */
import com.mycompany.Model.User;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AdminDashboardView extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardView
     */
    Login login = new Login();

    public AdminDashboardView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageTransaction = new javax.swing.JButton();
        btnKelolaBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        btnwkwk = new javax.swing.JButton();
        btnwkwk2 = new javax.swing.JButton();
        btnwkwk3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnManageTransaction.setBackground(new java.awt.Color(204, 204, 204));
        btnManageTransaction.setBorder(null);
        btnManageTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTransactionActionPerformed(evt);
            }
        });

        btnKelolaBook.setBackground(new java.awt.Color(204, 204, 204));
        btnKelolaBook.setBorder(null);
        btnKelolaBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBookActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel5.setText(" ADMIN CONTROL PANEL");

        btnSignOut.setBackground(new java.awt.Color(204, 204, 204));
        btnSignOut.setBorder(null);
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        btnwkwk.setText("Kelola Buku");
        btnwkwk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwkwkActionPerformed(evt);
            }
        });

        btnwkwk2.setText("Transaksi");
        btnwkwk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwkwk2ActionPerformed(evt);
            }
        });

        btnwkwk3.setText("Sign Out");
        btnwkwk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwkwk3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnManageTransaction)
                        .addGap(441, 441, 441)
                        .addComponent(btnKelolaBook)
                        .addGap(149, 149, 149)))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnwkwk3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnwkwk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnwkwk)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKelolaBook)
                    .addComponent(btnManageTransaction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnwkwk)
                    .addComponent(btnwkwk2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnwkwk3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBookActionPerformed
        // TODO add your handling code here:
        new ManageBookView().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaBookActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin sign out?", "Konfirmasi Sign Out", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            System.out.println("Sign out berhasil.");
            dispose();
            login.setVisible(true);
        } else if (response == JOptionPane.NO_OPTION) {
            System.out.println("Sign out dibatalkan.");

        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("Dialog ditutup tanpa respons.");
            // Tambahkan logika ketika dialog ditutup tanpa respons di sini
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnManageTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTransactionActionPerformed
        // TODO add your handling code here:
        new ManageTransactionView().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnManageTransactionActionPerformed

    private void btnwkwk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwkwk2ActionPerformed
        // TODO add your handling code here:
        new ManageTransactionView().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnwkwk2ActionPerformed

    private void btnwkwkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwkwkActionPerformed
        // TODO add your handling code here:
        new ManageBookView().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnwkwkActionPerformed

    private void btnwkwk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwkwk3ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Anda yakin ingin sign out?", "Konfirmasi Sign Out", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            System.out.println("Sign out berhasil.");
            dispose();
            login.setVisible(true);
        } else if (response == JOptionPane.NO_OPTION) {
            System.out.println("Sign out dibatalkan.");

        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("Dialog ditutup tanpa respons.");
            // Tambahkan logika ketika dialog ditutup tanpa respons di sini
        }
    }//GEN-LAST:event_btnwkwk3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaBook;
    private javax.swing.JButton btnManageTransaction;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnwkwk;
    private javax.swing.JButton btnwkwk2;
    private javax.swing.JButton btnwkwk3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
